---
title: "EpiRecIntegration"
author: "MSBR"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width = 24,fig.height = 22,warning = FALSE,message = FALSE)
```

## Introduction

This script analyzes endothelial niche signaling in the BEFM project

## Set WD
```{r message=F}
# Set WD
setwd("/Users/msbr/Library/CloudStorage/GoogleDrive-michasam.raredon@yale.edu/.shortcut-targets-by-id/1VLqBlyzO-Qad5O2kbwXkBRh_1cQho39t/Engineered Lung Paper/Global_Connectomics")
```

## Packages
```{r}
require(Seurat)
require(NICHES)
require(dplyr)
require(ggthemes)
require(ggplot2)
require(cowplot)
require(knitr)
```

## Load Epi Rec from save
```{r}
load("~/Library/CloudStorage/GoogleDrive-michasam.raredon@yale.edu/.shortcut-targets-by-id/1VLqBlyzO-Qad5O2kbwXkBRh_1cQho39t/Engineered Lung Paper/Global_Connectomics/epi.rec.Robj")
```

## Inspect
```{r}
epi.rec
```

## Update to v5
```{R}
epi.rec <- UpdateSeuratObject(epi.rec)
epi.rec
```
## Split for integration
```{R}
epi.rec[["CellToCell"]] <- split(epi.rec[["CellToCell"]], f = epi.rec$orig.ident)
epi.rec
```
## One line integration, multiple techniques:
```{R}
# Preprocess the split object
epi.rec <- FindVariableFeatures(epi.rec)
epi.rec <- ScaleData(epi.rec)
epi.rec <- RunPCA(epi.rec)
# Integrate with CCA
epi.rec <- IntegrateLayers(object = epi.rec, method = CCAIntegration,
  orig.reduction = "pca", new.reduction = "integrated.cca",
  verbose = FALSE,assay = 'CellToCell')
# Integrate with RPCA
epi.rec <- IntegrateLayers(object = epi.rec, method = RPCAIntegration,
  orig.reduction = "pca", new.reduction = "integrated.rpca",
  verbose = FALSE
)
# Integrate with Harmony
epi.rec <- IntegrateLayers(object = epi.rec, method = HarmonyIntegration,
  orig.reduction = "pca", new.reduction = "harmony",
  verbose = FALSE
)
# Integrate with FastMNN
# epi.rec <- IntegrateLayers(object = epi.rec, method = FastMNNIntegration,
#   new.reduction = "integrated.mnn",
#   verbose = FALSE
# )
```
## Cluster
```{R}

## PCA
ElbowPlot(epi.rec,reduction = 'pca',ndims = 50)
epi.rec <- RunUMAP(epi.rec, reduction = "pca", dims = 1:20, reduction.name = "umap.pca")
epi.rec <- FindNeighbors(epi.rec, reduction = "pca", dims = 1:20)
epi.rec <- FindClusters(epi.rec, resolution = 0.1, cluster.name = "pca_clusters")
p0 <- DimPlot(
  epi.rec,
  reduction = "umap.pca",
  group.by = c('class.Sending',"Dataset2.Sending", "orig.ident", "pca_clusters"),
  combine = FALSE, label.size = 2,shuffle = T)
p0 <- cowplot::plot_grid(plotlist = p0,nrow = 1)

## CCA
epi.rec <- FindNeighbors(epi.rec, reduction = "integrated.cca", dims = 1:20)
epi.rec <- FindClusters(epi.rec, resolution = 0.1, cluster.name = "cca_clusters")
epi.rec <- RunUMAP(epi.rec, reduction = "integrated.cca", dims = 1:20, reduction.name = "umap.cca")
p1 <- DimPlot(
  epi.rec,
  reduction = "umap.cca",
  group.by = c('class.Sending',"Dataset2.Sending", "orig.ident", "pca_clusters"),
  combine = FALSE, label.size = 2,shuffle = T)
p1 <- cowplot::plot_grid(plotlist = p1,nrow = 1)

## RPCA
epi.rec <- FindNeighbors(epi.rec, reduction = "integrated.rpca", dims = 1:20)
epi.rec <- FindClusters(epi.rec, resolution = 0.1, cluster.name = "rpca_clusters")
epi.rec <- RunUMAP(epi.rec, reduction = "integrated.rpca", dims = 1:20, reduction.name = "umap.rpca")
p2 <- DimPlot(
  epi.rec,
  reduction = "umap.rpca",
  group.by = c('class.Sending',"Dataset2.Sending", "orig.ident", "pca_clusters"),
  combine = FALSE, label.size = 2,shuffle = T)
p2 <- cowplot::plot_grid(plotlist = p2,nrow = 1)

## Harmony
epi.rec <- FindNeighbors(epi.rec, reduction = "harmony", dims = 1:20)
epi.rec <- FindClusters(epi.rec, resolution = 0.1, cluster.name = "harmony_clusters")
epi.rec <- RunUMAP(epi.rec, reduction = "harmony", dims = 1:20, reduction.name = "umap.harmony")
p3 <- DimPlot(
  epi.rec,
  reduction = "umap.harmony",
  group.by = c('class.Sending',"Dataset2.Sending", "orig.ident", "pca_clusters"),
  combine = FALSE, label.size = 2,shuffle = T)
p3 <- cowplot::plot_grid(plotlist = p3,nrow = 1)

```

## Plot to compare integration techniques
```{r}
cowplot::plot_grid(p0,p1,p2,p3,nrow = 4)

png(filename = 'EpiRecIntegration.png',width = 24,height = 24,units = 'in',res = 300)
cowplot::plot_grid(p0,p1,p2,p3,nrow = 4)
dev.off()
```

# Experiment with unified variable features?
```{r}
# split by sample
epi.rec.split <- SplitObject(epi.rec,split.by = 'orig.ident')

# Compute variable features for each sample individually
var.features.use <- c()
for(i in 1:length(epi.rec.split)){
  epi.rec.split[[i]] <- FindVariableFeatures(epi.rec.split[[i]],nfeatures = 1000)
  var.features.use <- c(var.features.use,VariableFeatures(epi.rec.split[[i]]))
}

# rules-based selection of features
# only use if internally variable within at least n tissues
table(var.features.use)
table(var.features.use)>4
which(table(var.features.use)>4)
var.features.use <- names(which(table(var.features.use)>4))
length(var.features.use)
```

```{r}
epi.rec <- JoinLayers(epi.rec)
epi.rec <- RunPCA(epi.rec,
                  features = var.features.use,
                  reduction.name = 'pca.custom')
ElbowPlot(epi.rec,reduction = 'pca.custom' ,ndims = 50)
epi.rec <- RunUMAP(epi.rec,reduction = 'pca.custom',reduction.name = 'umap.custom',dims = 1:20)
epi.rec <- FindNeighbors(epi.rec,reduction = 'pca.custom',dims = 1:20)
epi.rec <- FindClusters(epi.rec,resolution = 0.1)

p4 <- DimPlot(
  epi.rec,
  reduction = "umap.custom",
  group.by = c('class.Sending',"Dataset2.Sending", "orig.ident", "pca_clusters"),
  combine = FALSE, label.size = 2,shuffle = T)
p4 <- cowplot::plot_grid(plotlist = p4,nrow = 1)

```

